package computationEngine.SparkJobs;

import org.apache.spark.sql.SparkSession;
import scala.Serializable;

import java.util.concurrent.Callable;

/**
 * Print the links which are generated by another sparkjob to the console. This class is primarily for test usage
 * <p>
 * TODO modify the constructor to accept <RDD,SparkSession>. Each SparkJob should be capable to close the session it used.
 */
public class LinkPrintSparkJob implements SparkJob {
    LinkGenerationSparkJob linkGenJob;

    public LinkPrintSparkJob(LinkGenerationSparkJob linkGenJob) {
        this.linkGenJob = linkGenJob;
    }


    @Override
    public LinkPrintSparkJob call() throws Exception {
        getSession();
        linkGenJob.call();
        linkGenJob.linkRDD.collect().forEach(x -> System.out.println(x.toString()));
        return this;
    }

    @Override
    public SparkSession getSession() {
        return linkGenJob.getSession();
    }

    @Override
    public void closeSession() {
        linkGenJob.closeSession();
    }
}
